//establish queryString from the url
const queryString = window.location.search;
//establish params as the new URLSearchParams from the queryString
const params = new URLSearchParams(queryString);
//establish chosenState as the state value from the URL
const chosenState = params.get('state');
//establish headerElement as the statetitle element
const headerElement = document.querySelector('#stateTitle');
//headerelement inner text is set to the state parameter
headerElement.innerText = chosenState;
//establishing a state object with information about every state
const states = {
    "Alabama": {
        "stateFlower": "Camellia",
        "stateBird": "Yellowhammer", 
        "stateCapital":"Montgomery",
        "largestCity":"Birmingham",
        "stateNickname":"The Heart of Dixie",
        "statehood":"1819 - 22nd State",
        "stateAbbreviation":"AL",
        "notableMusicians":"Nat King Cole",
        "stateFood": "Lane Cake",       
    }, 
    "Alaska": {
        "stateFlower": "Forget-Me-Not",
        "stateBird": "Willow Ptarmigan", 
        "stateCapital":"Juneau",
        "largestCity":"Anchorage",
        "stateNickname":"The Last Frontier",
        "statehood":"1959 - 49th State",
        "stateAbbreviation":"AK",
        "notableMusicians":"Jewel",
        "stateFood": "Giant King Salmon",       
    },
    "Arizona": {
        "stateFlower": "Saguaro Cactus Blossom",
        "stateBird": "Cactus Wren", 
        "stateCapital":"Phoenix",
        "largestCity":"Phoenix",
        "stateNickname":"The Grand Canyon State",
        "statehood":"1912 - 48th State",
        "stateAbbreviation":"AZ",
        "notableMusicians":"Stevie Nicks",
        "stateFood": "Apache Trout",       
    },
    "Arkansas": {
        "stateFlower": "Apple Blossom",
        "stateBird": "Mockingbird", 
        "stateCapital":"Little Rock",
        "largestCity":"Little Rock",
        "stateNickname":"The Natural State",
        "statehood":"1836 - 25th State",
        "stateAbbreviation":"AR",
        "notableMusicians":"Johnny Cash",
        "stateFood": "Rice",       
    },
    "California": {
        "stateFlower": "California Poppy",
        "stateBird": "California Valley Quail", 
        "stateCapital":"Sacramento",
        "largestCity":"Los Angeles",
        "stateNickname":"The Golden State",
        "statehood":"1850 - 31st State",
        "stateAbbreviation":"CA",
        "notableMusicians":"Snoop Dogg",
        "stateFood": "Pistachios",       
    },
    "Colorado": {
        "stateFlower": "White and Lavender Columbine",
        "stateBird": "Lark Bunting", 
        "stateCapital":"Denver",
        "largestCity":"Denver",
        "stateNickname":"The Centennial State",
        "statehood":"1876 - 38th State",
        "stateAbbreviation":"CO",
        "notableMusicians":"The Lumineers",
        "stateFood": "The Snowball",       
    },
    "Connecticut": {
        "stateFlower": "Mountain Laurel",
        "stateBird": "American Robin", 
        "stateCapital":"Hartford",
        "largestCity":"Bridgeport",
        "stateNickname":"The Constitution State",
        "statehood":"1788 - 5th State",
        "stateAbbreviation":"CT",
        "notableMusicians":"John Mayer",
        "stateFood": "Pizza",       
    },
    "Delaware": {
        "stateFlower": "Peach Blossom",
        "stateBird": "Blue Hen", 
        "stateCapital":"Dover",
        "largestCity":"Wilmington",
        "stateNickname":"The First State",
        "statehood":"1787 - 1st State",
        "stateAbbreviation":"DE",
        "notableMusicians":"Jimmie Allen",
        "stateFood": "Peach Pie",       
    },
    "Florida": {
        "stateFlower": "Orange Blossom",
        "stateBird": "Mockingbird", 
        "stateCapital":"Tallahassee",
        "largestCity":"Jacksonville",
        "stateNickname":"The Sunshine State",
        "statehood":"1845 - 27th State",
        "stateAbbreviation":"FL",
        "notableMusicians":"Ariana Grande",
        "stateFood": "Oranges",       
    },
    "Georgia": {
        "stateFlower": "Cherokee Rose",
        "stateBird": "Brown Thrasher", 
        "stateCapital":"Atlanta",
        "largestCity":"Atlanta",
        "stateNickname":"The Peach State",
        "statehood":"1788 - 4th State",
        "stateAbbreviation":"GA",
        "notableMusicians":"André 3000",
        "stateFood": "Grits",       
    },
    "Hawaii": {
        "stateFlower": "Yellow Hibiscus",
        "stateBird": "Nene", 
        "stateCapital":"Honolulu",
        "largestCity":"Honolulu",
        "stateNickname":"The Aloha State",
        "statehood":"1959 - 50th State",
        "stateAbbreviation":"HI",
        "notableMusicians":"Israel Kamakawiwo'ole",
        "stateFood": "Saimin",       
    },
    "Idaho": {
        "stateFlower": "Syringa",
        "stateBird": "Mountain Bluebird", 
        "stateCapital":"Boise",
        "largestCity":"Boise",
        "stateNickname":"The Gem State",
        "statehood":"1890 - 43rd State",
        "stateAbbreviation":"ID",
        "notableMusicians":"Josh Ritter",
        "stateFood": "Potatoes",       
    },
    "Illinois": {
        "stateFlower": "Violet",
        "stateBird": "Northern Cardinal", 
        "stateCapital":"Springfield",
        "largestCity":"Chicago",
        "stateNickname":"The Prairie State",
        "statehood":"1818 - 21st State",
        "stateAbbreviation":"IL",
        "notableMusicians":"Miles Davis",
        "stateFood": "Popcorn",       
    },
    "Indiana": {
        "stateFlower": "Peony",
        "stateBird": "Cardinal", 
        "stateCapital":"Indianapolis",
        "largestCity":"Indianapolis",
        "stateNickname":"The Hoosier State",
        "statehood":"1816 - 19th State",
        "stateAbbreviation":"IN",
        "notableMusicians":"Michael Jackson",
        "stateFood": "Sugar Cream Pie",       
    },
    "Iowa": {
        "stateFlower": "Wild Rose",
        "stateBird": "Eastern Goldfinch", 
        "stateCapital":"Des Moines",
        "largestCity":"Des Moines",
        "stateNickname":"The Hawkeye State",
        "statehood":"1846 - 29th State",
        "stateAbbreviation":"IA",
        "notableMusicians":"Adam Young",
        "stateFood": "Sweet Potato",       
    },
    "Kansas": {
        "stateFlower": "Sunflower",
        "stateBird": "Western Meadowlark", 
        "stateCapital":"Topeka",
        "largestCity":"Wichita",
        "stateNickname":"The Sunflower State",
        "statehood":"1861 - 34th State",
        "stateAbbreviation":"KS",
        "notableMusicians":"Janelle Monáe",
        "stateFood": "Sandhill Plum",       
    },
    "Kentucky": {
        "stateFlower": "Goldenrod",
        "stateBird": "Cardinal", 
        "stateCapital":"Frankfort",
        "largestCity":"Louisville",
        "stateNickname":"The Bluegrass State",
        "statehood":"1792 - 15th State",
        "stateAbbreviation":"KY",
        "notableMusicians":"Chris Stapleton",
        "stateFood": "Blackberry",       
    },
    "Louisiana": {
        "stateFlower": "Magnolia",
        "stateBird": "Brown Pelican", 
        "stateCapital":"Baton Rouge",
        "largestCity":"New Orleans",
        "stateNickname":"The Pelican State",
        "statehood":"1812 - 18th State",
        "stateAbbreviation":"LA",
        "notableMusicians":"Louis Armstrong",
        "stateFood": "Gumbo",       
    },
    "Maine": {
        "stateFlower": "White Pinecone and Tassel",
        "stateBird": "Black-Capped Chickadee", 
        "stateCapital":"Augusta",
        "largestCity":"Portland",
        "stateNickname":"The Pine Tree State",
        "statehood":"1820 - 23rd State",
        "stateAbbreviation":"ME",
        "notableMusicians":"Howie Day",
        "stateFood": "Whoopie Pie",       
    },
    "Maryland": {
        "stateFlower": "Black-Eyed Susan",
        "stateBird": "Baltimore Oriole", 
        "stateCapital":"Annapolis",
        "largestCity":"Baltimore",
        "stateNickname":"The Old Line State",
        "statehood":"1788 - 7th State",
        "stateAbbreviation":"MD",
        "notableMusicians":"Billie Holiday",
        "stateFood": "Smith Island Cake",       
    },
    "Massachusetts": {
        "stateFlower": "Mayflower",
        "stateBird": "Black-Capped Chickadee", 
        "stateCapital":"Boston",
        "largestCity":"Boston",
        "stateNickname":"The Bay State",
        "statehood":"1788 - 6th State",
        "stateAbbreviation":"MA",
        "notableMusicians":"Donna Summer",
        "stateFood": "Chocolate Chip Cookie",       
    },
    "Michigan": {
        "stateFlower": "Apple Blossom",
        "stateBird": "American Robin", 
        "stateCapital":"Lansing",
        "largestCity":"Detroit",
        "stateNickname":"The Wolverine State",
        "statehood":"1837 - 26th State",
        "stateAbbreviation":"MI",
        "notableMusicians":"Stevie Wonder",
        "stateFood": "Brook Trout",       
    },
    "Minnesota": {
        "stateFlower": "Pink and White Lady Slipper",
        "stateBird": "Common Loon", 
        "stateCapital":"St. Paul",
        "largestCity":"Minneapolis",
        "stateNickname":"The North Star State",
        "statehood":"1858 - 32nd State",
        "stateAbbreviation":"MN",
        "notableMusicians":"Prince",
        "stateFood": "Blueberry Muffin",       
    },
    "Mississippi": {
        "stateFlower": "Magnolia",
        "stateBird": "Mockingbird", 
        "stateCapital":"Jackson",
        "largestCity":"Jackson",
        "stateNickname":"The Magnolia State",
        "statehood":"1817 - 20th State",
        "stateAbbreviation":"MS",
        "notableMusicians":"Elvis",
        "stateFood": "Mississippi Mud Pie",       
    },
    "Missouri": {
        "stateFlower": "White Hawthorn",
        "stateBird": "Bluebird", 
        "stateCapital":"Jefferson City",
        "largestCity":"Kansas City",
        "stateNickname":"The Show Me State",
        "statehood":"1821 - 24th State",
        "stateAbbreviation":"MO",
        "notableMusicians":"Josephine Baker",
        "stateFood": "Ice Cream Cone",       
    },
    "Montana": {
        "stateFlower": "Bitterroot",
        "stateBird": "Western Meadowlark", 
        "stateCapital":"Helena",
        "largestCity":"Billings",
        "stateNickname":"The Treasure State",
        "statehood":"1889 - 41st State",
        "stateAbbreviation":"MT",
        "notableMusicians":"Jeff Ament",
        "stateFood": "Steak",       
    },
    "Nebraska": {
        "stateFlower": "Goldenrod",
        "stateBird": "Western Meadowlark", 
        "stateCapital":"Lincoln",
        "largestCity":"Omaha",
        "stateNickname":"The Cornhusker State",
        "statehood":"1867 - 37th State",
        "stateAbbreviation":"NE",
        "notableMusicians":"James Valentine",
        "stateFood": "Runza Sandwich",       
    },
    "Nevada": {
        "stateFlower": "Sagebrush",
        "stateBird": "Mountain Bluebird", 
        "stateCapital":"Carson City",
        "largestCity":"Las Vegas",
        "stateNickname":"The Silver State",
        "statehood":"1864 - 36th State",
        "stateAbbreviation":"NV",
        "notableMusicians":"Brandon Flowers",
        "stateFood": "Shrimp Cocktail",       
    },
    "New Hampshire": {
        "stateFlower": "Purple Lilac",
        "stateBird": "Purple Finch", 
        "stateCapital":"Concord",
        "largestCity":"Manchester",
        "stateNickname":"The Granite State",
        "statehood":"1788 - 9th State",
        "stateAbbreviation":"NH",
        "notableMusicians":"Ray LaMontagne",
        "stateFood": "Pumpkins",       
    },
    "New Jersey": {
        "stateFlower": "Common Violet",
        "stateBird": "Eastern Goldfinch", 
        "stateCapital":"Trenton",
        "largestCity":"Newark",
        "stateNickname":"The Garden State",
        "statehood":"1787 - 3rd State",
        "stateAbbreviation":"NJ",
        "notableMusicians":"Bruce Springsteen",
        "stateFood": "Northern Highbush Blueberry",       
    },
    "New Mexico": {
        "stateFlower": "Yucca",
        "stateBird": "Greater Roadrunner", 
        "stateCapital":"Santa Fe",
        "largestCity":"Albuquerque",
        "stateNickname":"Land of Enchantment",
        "statehood":"1912 - 47th State",
        "stateAbbreviation":"NM",
        "notableMusicians":"Al Hurricane",
        "stateFood": "Chile",       
    },
    "New York": {
        "stateFlower": "Rose",
        "stateBird": "Bluebird", 
        "stateCapital":"Albany",
        "largestCity":"New York",
        "stateNickname":"The Empire State",
        "statehood":"1788 - 11th State",
        "stateAbbreviation":"NY",
        "notableMusicians":"Alicia Keys",
        "stateFood": "Apples",       
    },
    "North Carolina": {
        "stateFlower": "Flowering Dogwood",
        "stateBird": "Cardinal", 
        "stateCapital":"Raleigh",
        "largestCity":"Charlotte",
        "stateNickname":"The Tar Heel State",
        "statehood":"1789 - 12th State",
        "stateAbbreviation":"NC",
        "notableMusicians":"Nina Simone",
        "stateFood": "Scuppernong Grape",       
    },
    "North Dakota": {
        "stateFlower": "Wild Prairie Rose",
        "stateBird": "Western Meadowlark", 
        "stateCapital":"Bismarck",
        "largestCity":"Fargo",
        "stateNickname":"The Peace Garden State",
        "statehood":"1889 - 39th State",
        "stateAbbreviation":"ND",
        "notableMusicians":"Peggy Lee",
        "stateFood": "Chokecherries",       
    },
    "Ohio": {
        "stateFlower": "Red Carnation",
        "stateBird": "Cardinal", 
        "stateCapital":"Columbus",
        "largestCity":"Columbus",
        "stateNickname":"The Buckeye State",
        "statehood":"1803 - 17th State",
        "stateAbbreviation":"OH",
        "notableMusicians":"Tracy Chapman",
        "stateFood": "Pawpaw",       
    },
    "Oklahoma": {
        "stateFlower": "Oklahoma Rose",
        "stateBird": "Scissor-Tailed Flycatcher", 
        "stateCapital":"Oklahoma City",
        "largestCity":"Oklahoma City",
        "stateNickname":"The Sooner State",
        "statehood":"1907 - 46th State",
        "stateAbbreviation":"OK",
        "notableMusicians":"Reba McEntire",
        "stateFood": "Fried Okra",       
    },
    "Oregon": {
        "stateFlower": "Oregon Grape",
        "stateBird": "Western Meadowlark", 
        "stateCapital":"Salem",
        "largestCity":"Portland",
        "stateNickname":"The Beaver State",
        "statehood":"1859 - 33rd State",
        "stateAbbreviation":"OR",
        "notableMusicians":"Esperanza Spalding",
        "stateFood": "Hazelnuts",       
    },
    "Pennsylvania": {
        "stateFlower": "Mountain Laurel",
        "stateBird": "Ruffed Grouse", 
        "stateCapital":"Harrisburg",
        "largestCity":"Philadelphia",
        "stateNickname":"The Keystone State",
        "statehood":"1787 - 2nd State",
        "stateAbbreviation":"PA",
        "notableMusicians":"Taylor Swift",
        "stateFood": "Shoofly Pie",       
    },
    "Rhode Island": {
        "stateFlower": "Violet",
        "stateBird": "Rhode Island Red Chicken", 
        "stateCapital":"Providence",
        "largestCity":"Providence",
        "stateNickname":"The Ocean State",
        "statehood":"1790 - 13th State",
        "stateAbbreviation":"RI",
        "notableMusicians":"Jeffrey Osborne",
        "stateFood": "Calamari",       
    },
    "South Carolina": {
        "stateFlower": "Yellow Jessamine",
        "stateBird": "Carolina Wren", 
        "stateCapital":"Columbia",
        "largestCity":"Columbia",
        "stateNickname":"The Palmetto State",
        "statehood":"1788 - 8th State",
        "stateAbbreviation":"SC",
        "notableMusicians":"Lee Brice",
        "stateFood": "Barbecue",       
    },
    "South Dakota": {
        "stateFlower": "Pasque Flower",
        "stateBird": "Ring-Necked Pheasant", 
        "stateCapital":"Pierre",
        "largestCity":"Sioux Falls",
        "stateNickname":"The Mount Rushmore State",
        "statehood":"1889 - 40th State",
        "stateAbbreviation":"SD",
        "notableMusicians":"EMA",
        "stateFood": "Chislic",       
    },
    "Tennessee": {
        "stateFlower": "Iris",
        "stateBird": "Mockingbird", 
        "stateCapital":"Nashville",
        "largestCity":"Memphis",
        "stateNickname":"The Volunteer State",
        "statehood":"1796 - 16th State",
        "stateAbbreviation":"TN",
        "notableMusicians":"Dolly Parton",
        "stateFood": "Tomatoes",       
    },
    "Texas": {
        "stateFlower": "Bluebonnet",
        "stateBird": "Mockingbird", 
        "stateCapital":"Austin",
        "largestCity":"Houston",
        "stateNickname":"The Lone Star State",
        "statehood":"1845 - 28th State",
        "stateAbbreviation":"TX",
        "notableMusicians":"Willie Nelson",
        "stateFood": "Chili",       
    },
    "Utah": {
        "stateFlower": "Sego Lily",
        "stateBird": "California Gull", 
        "stateCapital":"Salt Lake City",
        "largestCity":"Salt Lake City",
        "stateNickname":"The Beehive State",
        "statehood":"1896 - 45th State",
        "stateAbbreviation":"UT",
        "notableMusicians":"David Archuleta",
        "stateFood": "Jell-O",       
    },
    "Vermont": {
        "stateFlower": "Red Clover",
        "stateBird": "Hermit Thrush", 
        "stateCapital":"Montpelier",
        "largestCity":"Burlington",
        "stateNickname":"The Green Mountain State",
        "statehood":"1791 - 14th State",
        "stateAbbreviation":"VT",
        "notableMusicians":"Anaïs Mitchell",
        "stateFood": "Maple",       
    },
    "Virginia": {
        "stateFlower": "American Dogwood",
        "stateBird": "Northern Cardinal", 
        "stateCapital":"Richmond",
        "largestCity":"Virginia Beach",
        "stateNickname":"The Old Dominion State",
        "statehood":"1788 - 10th State",
        "stateAbbreviation":"VA",
        "notableMusicians":"Patsy Cline",
        "stateFood": "Cured Country Ham",       
    },
    "Washington": {
        "stateFlower": "Coast Rhododendron",
        "stateBird": "Goldfinch", 
        "stateCapital":"Olympia",
        "largestCity":"Seattle",
        "stateNickname":"The Evergreen State",
        "statehood":"1889 - 42nd State",
        "stateAbbreviation":"WA",
        "notableMusicians":"Macklemore",
        "stateFood": "Walla Walla Sweet Onion",       
    },
    "District of Columbia": {
        "stateFlower": "American Beauty Rose",
        "stateBird": "Wood Thrush", 
        "stateCapital":"Capital of the United States",
        "largestCity":"There are no cities within the District of Columbia",
        "stateNickname":"Our Nation's Capital",
        "statehood":"1790 - Not a city or a state",
        "stateAbbreviation":"DC",
        "notableMusicians":"Chuck Brown",
        "stateFood": "Half-Smoke",       
    },
    "West Virginia": {
        "stateFlower": "Rhododendron",
        "stateBird": "Cardinal", 
        "stateCapital":"Charleston",
        "largestCity":"Charleston",
        "stateNickname":"The Mountain State",
        "statehood":"1863 - 35th State",
        "stateAbbreviation":"WV",
        "notableMusicians":"Bill Withers",
        "stateFood": "Pepperoni Rolls",       
    },
    "Wisconsin": {
        "stateFlower": "Wood Violet",
        "stateBird": "American Robin", 
        "stateCapital":"Madison",
        "largestCity":"Milwaukee",
        "stateNickname":"The Badger State",
        "statehood":"1848 - 30th State",
        "stateAbbreviation":"WI",
        "notableMusicians":"Skylar Grey",
        "stateFood": "Kringle",       
    },
    "Wyoming": {
        "stateFlower": "Indian Paintbrush",
        "stateBird": "Meadowlark", 
        "stateCapital":"Cheyenne",
        "largestCity":"Cheyenne",
        "stateNickname":"The Equality State",
        "statehood":"1890 - 44th State",
        "stateAbbreviation":"WY",
        "notableMusicians":"Chris LeDoux",
        "stateFood": "Bison",       
    },
};
//setting headerelement to equal the content of the flower
const headerElement2= document.querySelector('.card-text-flower');
//setting the innertext to equal the flower of the selected state
headerElement2.innerText=states[chosenState].stateFlower;
//setting headerelement to equal the content of the bird
const headerElement3= document.querySelector('.card-text-bird');
//setting the innertext to equal the bird of the selected state
headerElement3.innerText=states[chosenState].stateBird;
//setting headerelement to equal the content of the capital
const headerElement4= document.querySelector('.card-text-capital');
//setting the innertext to equal the capital of the selected state
headerElement4.innerText=states[chosenState].stateCapital;
//setting headerelement to equal the content of the largest city
const headerElement5= document.querySelector('.card-text-city');
//setting the innertext to equal the largest city of the selected state
headerElement5.innerText=states[chosenState].largestCity;
//setting headerelement to equal the content of the nickname
const headerElement6= document.querySelector('.card-text-nickname');
//setting the innertext to equal the nickname of the selected state
headerElement6.innerText=states[chosenState].stateNickname;
//setting headerelement to equal the content of the year of statehood
const headerElement7= document.querySelector('.card-text-statehood');
//setting the innertext to equal the year of statehood of the selected state
headerElement7.innerText=states[chosenState].statehood;
//setting headerelement to equal the content of the abbreviation
const headerElement8= document.querySelector('.card-text-abbreviation');
//setting the innertext to equal the abbreviation of the selected state
headerElement8.innerText=states[chosenState].stateAbbreviation;
//setting headerelement to equal the content of the musician
const headerElement9= document.querySelector('.card-text-musician');
//setting the innertext to equal the musician of the selected state
headerElement9.innerText=states[chosenState].notableMusicians;
//setting headerelement to equal the content of the food
const headerElement10= document.querySelector('.card-text-food');
//setting the innertext to equal the food of the selected state
headerElement10.innerText=states[chosenState].stateFood;